"use strict";

const listItemsObj = [
	{
		product: "Black Sweatshirt",
		buyingPrice: "₦3,000",
		quantity: 10,
		thresholdValue: 12,
		category: "Men's",
		availability: "In Stock",
	},
	{
		product: "Black Sweatshirt",
		buyingPrice: "₦3,000",
		quantity: 10,
		thresholdValue: 15,
		category: "Women's",
		availability: "Out of Stock",
	},
	{
		product: "Black Sweatshirt",
		buyingPrice: "₦3,000",
		quantity: 10,
		thresholdValue: 20,
		category: "Men's",
		availability: "Low Stock",
	},
	{
		product: "Timberland Boots",
		buyingPrice: "₦3,000",
		quantity: 10,
		thresholdValue: 25,
		category: "Footwears",
		availability: "In Stock",
	},
	{
		product: "Laptop Bag",
		buyingPrice: "₦3,000",
		quantity: 10,
		thresholdValue: 30,
		category: "Bags",
		availability: "Low Stock",
	},
	{
		product: "Black Sweatshirt",
		buyingPrice: "₦3,000",
		quantity: 10,
		thresholdValue: 35,
		category: "Unisex",
		availability: "Low Stock",
	},
	{
		product: "Pateek Philippi",
		buyingPrice: "₦3,000",
		quantity: 10,
		thresholdValue: 40,
		category: "Accessory",
		availability: "Out of Stock",
	},
	{
		product: "Black Sweatshirt",
		buyingPrice: "₦3,000",
		quantity: 10,
		thresholdValue: 20,
		category: "Men's",
		availability: "In Stock",
	},
];
